### ISSUE TITLE
galactic glitch upgrades not working

### ISSUE THREAD

**Issue by Darkwing3125** [glitchyfishys/AntimatterDimensions-V#1]
In the save I've attached below, despite having no dim boosts, one galaxy, less than 20 fourth dimensions, and more than 1e25 antimatter, the glitch upgrade "galactic limitation" is not unlocked.
Save:AntimatterDimensionsSavefileFormatAABeJztPFlz2zjSf2VKr6t18ZIo5k2WHY0brRolXUmYfUn6ASUjimiI5POxoXf7vXzcaFynJcXaczLdbySELDaDRABqNvuCnAcubdMeahleDdwP3LHLdceBP0cDDw0cdDnf0cNGg0bEgSXc8r9Mirwfvnjo9Pj8N7op2s20aG7ybOcBAXdXPe7kpoByW2K9ocagbexHcnYRRFbjgeB67jOYPnoek5Pt0azcKNg4vmTaDSJzvyxH40a6PYPTPV1vMvaD8CzyxlHg4aCdnm50aumfUaXl6COeva3c7HKT5Os3TZi82Ia0a0c5VkR30cNk8G7NspoPbTxWT0aKKs3TkHwDdsZpPZRsHafgT6N4c39sjfHPU0cG9u8Ha4vDekyxu9Ia7JIS7gQxAGXPCgajnoYdCYcWTZaPSaRq5YiNc0ae10a7mII0cenXT8aub0bq8nwH0bRgNtnKLX7TyBgM9cZvGuqFnamZnGVrtMYN0at0aYPE25Q8cZHJznjYgHD57o9FQ0cA0cCoes6w8lk6Bz0cCxtW87jizfQACXTTbZRw0bVRuKpZwrBYbPW0bzhi4E0bc0aL5ZdgJL9sWMa0b7M8LnPNw4E4k2B0cLLxWveUPV1kALDhNndxknSoiKeMuyjOcbjtdOXlQ7luG3uK0aqnhOv3vG6WQFh2M0a9C6NwHPmuH0azGnu0bOQtybyfBb4b7jwxX1zd3ccOS43z7aN8JxWYpdmfGGJ7RxXgRMZl0aH330bB0ciL44dRx4lCqjk281RLOQab7o0a0ari9ud596atcTpBi9rm0aKoO0cATeJNX9cdcS8skrZFZZwUc1bxtd7qi4iyTGHdFwmnwnRSLm2xfbgWIhCZ8qbesIhLTeho36QOXqHoz0a8iMmjLACcBRBoH8z7TZiuMlRQahd4eDL70bmmy3XcvlwjLt0aM6vaPN6K5RNyykW8MPQDnjZ3hPfk8PuMPxxkDLkzvqclJ9FxghKPCMnSXdpcYcMUeVri2bEvBuYKKTpnX8zlJorXGldnuYnkLiUg4EhEHaclMKRcyJYdWiygK9sJoX5A98YQ7fwHZDbwrS45MvnRS0c0aI6SOzm0b6L6LHyXF5NWPls3USCI2G0c0azJLheHgDfq48ARpQwHWg0ayHLDulrp4i9a7N7gVc0avzymhwS0cdrBxj9ysPBHDjb5kYNFP3Iw10cmho7k0cdDTvDUa7PXIq1aV3eCZfkDT0cq9XHFggvr50bLc2JxKg4iP0abJbu6yPpZOM2NB0cIjVPLWfqy0avQP0a7TmySZqxJi0cyvJ0cUuY0cH9r0aXGb4pHvFdP0aXGI0b8RmCWX0a60cM6gu80cgxwVODu2SXNW0cUg6vh0ck2AwTVt3PO4rOy2obq2Pyp76iaZ6nW8mf3dZK27TUMPfMGaGaluabNmOVNB0aON6REXf0acbZqj9fzFeusKuSngvqqlO0acChUQYuEEHcs7ye0b20b0aN5kpSI7HT14OMj5o1jEmnMxZ4YeDjcYeZ43HgVD1xmHwcjx0cHDouV7kjz0aoD7FB5EThKBp6juuOIzf0aQmgbeN4ILHN36IIFOZqAUeliWzAqx0cAPvrp0bBAh8H6HjcRT49BXQBd7IHwJ0bP5x448kwGE3CIIL9R851nTDwgjBCg90bHMYAmwDv2vNCDFiVSjN4cUM7jlGW4n8AcrGHC1Kx5xuv6A0axzlqEGL5agZCWv4iyV3l5chH0b0avAVRUKe0a0b6Tu8HS95tkKBcRsy0arhhndRzBUNy5Ziycaj8TMx0aqcyYQ0aqDqELtE8mYeSEaB6BmGlLdAtg58kkwIWJziL4AysTSM0bLB1JIbIgo0baI0acM4ctOR0ayED4CLE0bWiljZNZxW4vKyUpQZ0bwHMgdjbyY9iTj0cqrm2GasPTaUtfwdi7V7zP3mzSKMSXNNsOXk7YB8eUv64FA1WS6NssTzmleX0cqo0a5XG0bLx3zRUqBjoWx5OpiX2hyn8rX2Hmhxq50aMsy2X5Ng0bBrAMpyj3qH9eWOuhQNOLyXEHQJFn0b0bmFq2dB5YkuY1fXKi2u0btcAOdGmc6vRqkpZUpvRb9oKtqvmyWplgNfWwdY95WIIoGpoeUMIBPO9RqIEk0aBh2bSJ6OGQxY7uECrVGfAzcM2vxMtwEnYsF56cpwHfFf0bytA2HBFzGNb8N3sEZD0aWv0b1XF0bUXFNnDjbKSXp0bJxUSViMzZsx2ewHA3MkFwUcC7grLuh70aWhPENYc5OxvUDsjsNwEo58cTZGvkfqBFVPgV5iPBS9x11ZYvG0cglE1uSiK3Ykm6zbLrpB48n9RKA6PR8Uf0aqKtgWUXEgv5l3AiUzu0a551Fzth3vADsipHrj4A8IaRhdWCd7T30b0cDkcAwFD0bhQHFf8Pboef0cYkL8pU0bOxUBhveG9NmpiJwRiGH67KIiJ6v8oas0bCC0cvLzPl0bf1lhI1B1obRkD47WNyxHzgg20blHtyr0aJiF6ZcWPXhV5aunH6bEn2Bhk0b2jsDeWPFxvfquW0aT8fnb3a7GlqHcHKQ3p8IfiL48wg0ae9LF9ie40a0aWUIkbzs0cvP7t0ceHcPG27S0btnQjChlEcB9EI3HvwZ9JaN2ORytRxwVDRdZDdTju1KPGNcc8kjNQ9uH6i8KJP0aGS3AAvPwyOXd0cs0alyFYlX5d3TBAcnPEnZAqLwDDXESoDEYbXHgno2iEVzjI2cShXBHOp49lNYyRf6HWJdLS0b0bj4V7QGo5Wqnn7ZxiqcMZyS8St75Mydn0ajDTeiZF5jEKdom7lUUvWCXPYW6NIskF4zrT7c8Gpek5kAf8AgcsauHwZhCFsD39WCHs7wqwrUC0a0a0aVUfWcmGU30b0b0clPD98sZeKq0aH6HWhVgvtHzOwi5XVc7EUi0b5YJbHkjlzAg2n9mfUTccllU4Ee0a1B8cjGXtCzmS96QMbWYGz4Q33WN6P8bWFMUszJF3YJ2qMNEuk7o8LqUzmes1KWMpQ3PmCw0cP8vWVZufiHgd0bEfSesk3aJJhIzJLwP5OlqsL3QQsnmUDdqaFZpsmHJi6sAO0bJWjwcDLmKRjvTZFb5lCNvS0bEoY2WO8PFxju3WK0bzNOe40bp9qxO66QQRWvDeyrJLPJzI1Xvp720akCkeH9J1wdsZQZj6XHAJ0awwH0cCMZD0aLQbRBzrB4W0bzRtl0bZFg88IocVF5g0b3setc1fgpE0cC1bC70bQZU1W7hLANt9RgG2CnldyivwmdWAYm40bNLDI2rntIyi0b0bvGKxoYowchKmYh0bfZnmfhaskzvUvdtKYtegEAzZnjqtLMpHOJLJ10boEmVrXaBSeARFuoemLfn0aKKC1Sck2YSbBvbwXvos0aD1tZMGqA2C7c5OdlZZWgduFWpnX4lRti3IOu7ZL0c23xNez0bmlcVT25YsxXq363gplJk5dTCJWv4VyMciMzEv67i1nKGCItLsjtQXfJYzw6bxJMUmWbkqCIyBGWKJpYftbNWrCsyGjhb0byK0cgUOdxplmXtFdOQ4EJOdfmtUWiNgWWWIy0aTBFbkU4Om4L4tcjFW3nOFRWKtQT6CDYwhOfvvh0aCeQSzPXpUkBNSEjYvwutpTIqvvSiLVM4ZTgBfXU4HdeQ0cDpHwZJz0b65Sd4F25Js2jhTYRu6Td18uqBDo0bQPIqKLaS75kMbYoSZQ4dhKOnRcjjzFtV2fvcGPXa1alm0b4McBHaPCnkMIfcrMiDe2T40cwwuTmDRgNiG7SnQ0b40a0bnzRryANfC4lOC1SxeiudYOgKIuC0bJGYpVdiokt50cbAf3DFfLBmiMx1U4p9cpT0basvrdaLLGHdTPd9lKl3hx5Z7O0cA37iqu0bA2JYob45cc0ckb41Yj4NUfkzNUioQryk8zSQk7DhKwc6JV3lJWPH4oGnReywWQFSrr7n1V7D5cybO4390aV2RylBArtuMiKSpYommRpKIHjBc7Y91ww0a0aidEVpMDdpSnlyxtq5TJkMhlJfW1mlMXV3fD0acRXK9hNJ7omhP9viZkA0cE5kmKlkxsoygv0bhxR0cveimbmRXHLZevHr84WAsPkPxORGfEYl0bh8ir0bB0b0cCSf0akyUNrbGoFXrH9Q3TuTYx6CG23opHWFVL0aIXvWHXDcqnfY0abksqgaXZgVWcbK2nRD4BQrMo6rTmo3K8ts0c14ItRVGGjY67LErHjgFAz7mNyQHBU9RLRKu1ErHcNjlTI0bPX0a3wdCoh8t7TNphOn0abiSHtW3TZCqZyaChkWkoQDfMfgCiPFQej5oLMVJdk4sGYlZe0cwJIVWCkC3GJwvhWddVDFfcGEtGFgGR0bnyC49be87QBjf0as4ghCnyKT8DqoSMhL5IP0cPEXOSIeLVBRhY47EKe7yAGRmMmTVcS90b1gl4v0aOqt8wuAwFyrtEfBHUqvCGEgmUX4uWEbKDDFHHW9MdLAgR0bwIJIK8vnWmqchso7i0bTXqVK3VH0bxS3WgSRt1cvQwGZorRAPdIVT2zcKRT1TURMR1E866VY0cdPhbO88DJJPpqcHIiaJqrtJuuz10anEeDP0cANIyrQnMH4MspUCohyOO0bM1IMWVH0c9emM40bKOFw2bEmiBcF4WRrShDl0aObC0aeIK0a34qXEN4BFdgsFxaM3e0aplciIOAV5OlXfbuOA46gLL5XqamS7bQo0c7JUzCDxHw5kEEWNir0b0bC1p6Kdtj3ojmeM9Tf7V1s1VB4kOwOZ1xh5Ueu0aSDrcIK2qzHy5WlbwtK0cEm7TUgkJKbCOo0aSmvc7QVsGatt7Mf2Rslvay10aRrwxX3hd8wqYrlYnkkLgS7I2Zas1zywvnDYPiw0awS62Hhc1qOgUSCDeynVn0cX1E0bXwEDkob0bb14VCJKMCkv5IM3x10b0ap1OiQ0cjEHCTqdCpYteNKKu2LZ8PJ0a0a0bVqWapnAYBZxZ3R0bD39j9Z5od0a0af3ePI39EAfs0bS8tSeZjwSqbzxpveCczISYYJnXwHDKOC4VgAy7bN721AR97EWGtBuqfnjRFbfP0b2mB0ceHuUGNB6wqddpvd3Xb40aehUQWb0cmO3lkyIztB1Yot1RdvlZ0b1P2v0ci2pvUaSL5zkLDta9UHp0cZ1nL39BB89yX7LsCh2l3WoV54U6IQRvYoBTCSy9JQbNkwmpQtxVn95gUI5OAXIQ0aGMVawFR2dxV5eNGvqOIIODGTrGmFXvqw0azeT0cRbeEggD22F8qE5ezI0cALg9d3imQ0cJuVt0bdYyaLK0ard39eew32tYNIzypipKyfdbYD0bdfDV454v3QmvAAsfnsCJJ12BHt1mzpwiJYzt5nzopw0cRujjzMALzMebXZS4CVyYtGm1APn1QsCixJ0aOdjmkAN1V0aAWO4zoxvKJtLsczpZwiY0bY40a3Y0bW1fN1HS4dqvDTt7BAYHSEFuMowSVSpzyXPMiFMEpnZpiyknr97lzNl3UsHRif2YyXwHea16eDQdT8pWddcHsamnvseoM5bNWIF2hjFNChjNMREOGslImdFrmNmjnrKeKOFKJWvOOwuehKmSZKSuXZYN5cZ3TE71cIsgKGo24JCesdqLlUNLkG6JgX1gcUibfMJnc4qsN8zayvUtXmyKihFM0bEx270ccA0cOZ4QyxDbfU7y4WkPBFbbAcGtO99sAKbaUy519Na8mA3Yov39SHtMpXk0cZ8xHjqrbwxgKyjUOPKdIJBG2rPkw7UeBv0aI8z0bU97uPRVLn1xiPW6uDe20a8wevUO0a8aBVZVDCzIge2mrE9lbTDAYQHSTvdRBBe2OfCK32nH1pbgtEcSssVrlSEOzXgXSUoMxg0aH7MM1qmzZ71dvePNi0cUJWMUvNtiw3e7FBmCHppnNn0c0amzwcqT0b0cpObrEa9RrLnPLqGd3tr9dis4GlKwNGJfJqltNqEAhalp0aS7BsSV7LwEB6aRJF2ajf76OeX0cAcN0aJnTZAv87yF3asonjq9nqkouszLkE61OGsTPs1RRlk2cQ6ymO7IwTJOgRmQ3IGBX6SblLYxLsQij0bw0bkbiyhCda3XPXF3J1m2o0cM78qQh9PBCtPWMejPc0ay3d6cgjgr2uSyO2nMA7kqik3GPwh3q4Vkhs3nRcKyjn9XgD0cCVfAIt6jVY50cHSzCp1eNu7VzeFs0a930buieL0awg7u2hrV5J7OMBxKO3sAK12860c0cjb5cUAWQdVmIXYXN8Xr0aY0bXStcMv3EOGukj7xgybl4ACIzvj5Su473HrYujYGrlo946IXiodgAYwcwjeJGRSwNE6l8F0bG3cWWoZZveAdViG2cMkLWl5eVuYAy1n9JA0aA0baoEr9Ugfx1VG711yBBCitnQZ1KKY3c5YMw2nU1pLDChFBiGSlFEHcFPObVh740b1TtNcZo0bZeywMQghJpIG3KF1q2siAGFbnWIDHSEFf8C2mFWVGa0cORz1SsPtqwDI0bsApEnMdW7EAgH0cK8W0aJupgOqtGEw5cXFbpZZZxQYXxkpWivSLCym6bonRebcinksalNNznQJfrpKhrKqpHZXgdwRYGMqyDo0cMroTOcFKqC1PTXhJoTlEMEVKN9orUHHX47FZAyMHIVCwunq2DreitdkwodFGU3vojBoD15MmhCUGVr5gyxMGBFZqciJjqch9Hx0cwddMqFyaMYVkVOLW0bg0acVhqL0cdDImNZSRhzkp3SIV0aV85LWBg5JraXaXFXfLvHhcZ0bxevLUbU1RonVYWQQwKYHUnFgcexAXjQ0cHJv6TNoRT0b2lxE3lHvoZVY0aQUd6g7s4L0aU68cYjXJk3llRV5MUZ0aE0ciXwRSRnH40axxUN7YYkHSsxYyUq6k2TR9O9rvovVcjF2h4Dqh0aH4FaR1ZlLdTFXGk0bE9H8k5v9I3KHtneSPfub0bZTy917a3mUKutc2K84OxBtPfXne2IFLAx22KUD6eE8xdedxKtO0a0c5I3afeB5JCSnD7tKQHx8eEqOT8D7OeVHsrYCUptfxIBqJMesmiXbtbyiulp8y1x1odWR0a17VBpj0cssJHrCc7glrWANQpbtXaOApxJNZYjuYykQ0aG0bskWXqfrKrK0aN0cv7E9qBFkp2CwfrsH7aXuqVI6in75QIJcaJow60cdpZR0aAyotku1KLU0ayqhuuNonZ4fwNvsOpj3pMaGmrF158p0caxqViswqy7Ib9LRcySS90aXViVeLKFrzuzLo3QlKSnH0angbL1UUMfFujxuWcOUEwiYIAXwtjiBHk30aW660bbSJocAzdDdCnOGuvDrm2758qbslBdzvDVNWavuWlzz0bB62aAmCQj0akV7XPHdNO0b7yeOu4vaaIYk6us0bJHfnkX1LoZWxSvdk0a36v7jroNJKTDwcW7mVejXPz0c8H0aYIxdAEndOfSavefile

**Comment by glitchyfishys** [comment]
forgot some of them are progress locked so I added when you have to complete them (I could make them persistent)
(all of that stuff is under "player.glitch" others are under the celestials if you want cheat them)
