### ISSUE TITLE
TypeError: GlitchRealityUpgrades.all[4].effectOrDefault(...).pow is not a function

### ISSUE THREAD

**Issue by toilet45** [glitchyfishys/AntimatterDimensions-V#2]
**Describe the bug**
This error prevents the game from working

**To Reproduce**
1. Open the game
2. Check console

**Expected behavior**
The game to actually load and be able to buy AD1

**Additional context**
probably replace GlitchRealityUpgrades.all[4].effectOrDefault() with GlitchRealityUpgrade(5).effectOrDefault()?

**Comment by glitchyfishys** [comment]
effectOrDefault(value) returns the value if false (I put a Nubber not a Decimal)
