### ISSUE TITLE
Antimatter jumps to 1e1E300 if it is not being produced

### ISSUE THREAD

**Issue by James103** [glitchyfishys/AntimatterDimensions-V#5]
**Describe the bug**
As of 632865364782850ac0b4600d7cf0063f9e2cd586, starting the game instantly allows the player to Big Crunch, as Antimatter production is unconditionally set to 1e1E300 if it is zero.

**To Reproduce**
Start the game.
Notice you are able to Big Crunch immediately.
Break Infinity.
Notice Antimatter jumps to 1e1E300.

**Expected behavior**
Antimatter should not jump to 1e1E300 if it is not being produced.

**Additional context**
Another player reported this issue here: https://discord.com/channels/351476683016241162/1249497829081219122/1253125517050122261

**Comment by DEMEMZEA** [comment]
It also shoots to 1e1e300 at random points. my previous antimatter was close to 1e500000000

**Comment by glitchyfishys** [comment]
I was fixing free tickspeed witch would set multipliers to zero (some how 8th dim was zero)
