### ISSUE TITLE
almost done

### ISSUE THREAD

**Issue by glitchyfishys** [glitchyfishys/AntimatterDimensions-V#6]
I am changing numbers to decimal

**Comment by DEMEMZEA** [comment]
Oh, so that's what made the bug

**Comment by glitchyfishys** [comment]
almost done, testing time

**Comment by DEMEMZEA** [comment]
message = "Uncaught TypeError: player.records.recentRealities[0][1].lt is not a function"

**Comment by DEMEMZEA** [comment]
cannot use "pause 0.5s" in autobuyer

**Comment by glitchyfishys** [comment]
strange eternity challenge tab reactivity for player.antimatter
